<?php

/**
 * Active Collab configuration file
 *
 * Automatically generated by the installer script on 2017-03-15
 */

const ROOT = 'D:\Work\projects\nr10\projects\activecollab';
const ROOT_URL = 'http://pms.local';
const DB_HOST = 'localhost';
const DB_USER = 'root';
const DB_PASS = '';
const DB_NAME = 'activecollab2';
const ADMIN_EMAIL = 'scriptbaker@gmail.com';
const LICENSE_KEY = 'JOeV7h2HKl0qS5PVhL6g7pem8hTwiv0S0cC6ksCU/196570';
const APPLICATION_UNIQUE_KEY = 'JOeV7h2HKl0qS5PVhL6g7pem8hTwiv0S0cC6ksCU';

defined('CONFIG_PATH') or define('CONFIG_PATH', __DIR__);

require_once CONFIG_PATH . '/version.php';
require_once CONFIG_PATH . '/defaults.php';
